//==================================================
// This file contains the Excluded objects
// Generated By User: marcelo
// Format Version: 2
// Date: Fri Jan 17 16:57:42 2025
// ExclMode: default
//==================================================
CHECKSUM: "1706182284"
ANNOTATION: "The parameter EnableRspIntgGen is zero, so the condition will never hit."
INSTANCE:tb.dut.u_reg.u_reg_if.u_rsp_intg_gen
CHECKSUM: "4255502330"
ANNOTATION: "Becasuse of the data_in is a read-only register, the signals wr_en and wr_data are not applicable. So those lines 43 and 44 are not hit by the testbench."
INSTANCE:tb.dut.u_reg.u_data_in
CHECKSUM: "2099741489"
INSTANCE:tb.dut.u_reg.u_data_in.wr_en_data_arb
CHECKSUM: "2099741489"
ANNOTATION: "This logic can be excluded, the data_in_valid register is covered as expected. wr_en is unused in this case."
INSTANCE:tb.dut.u_reg.u_hw_straps_data_in_valid.wr_en_data_arb
CHECKSUM: "295805079"
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
INSTANCE:tb.dut.u_reg.u_masked_out_lower_mask
CHECKSUM: "295805079"
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
INSTANCE:tb.dut.u_reg.u_masked_out_upper_mask
CHECKSUM: "295805079"
ANNOTATION: "The masked_oe_lower_mask is accesible only by software, and not internally"
INSTANCE:tb.dut.u_reg.u_masked_oe_lower_mask
CHECKSUM: "295805079"
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
INSTANCE:tb.dut.u_reg.u_masked_oe_upper_mask
CHECKSUM: "295805079 2786204945"
INSTANCE: tb.dut.u_reg.u_masked_out_lower_mask
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
Block 2 "1004401251" "assign qs = d;"
CHECKSUM: "295805079 2786204945"
INSTANCE: tb.dut.u_reg.u_masked_oe_lower_mask
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
Block 2 "1004401251" "assign qs = d;"
CHECKSUM: "295805079 2786204945"
INSTANCE: tb.dut.u_reg.u_masked_out_upper_mask
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
Block 2 "1004401251" "assign qs = d;"
CHECKSUM: "295805079 2786204945"
INSTANCE: tb.dut.u_reg.u_masked_oe_upper_mask
ANNOTATION: "The masked_oe_lower_mask is only accesible by software. The signal related with d () is tied to zero. hw2reg.masked_out_lower.mask.d"
Block 2 "1004401251" "assign qs = d;"
CHECKSUM: "2920257930"
INSTANCE: tb.dut
ANNOTATION: "The assertion can be excluded, the testcase it will run multiples resets/sample_en operations to guarantee the randomization and coverage of different scenarios. If the assertion is on, it will fail for the following sample_en driven after every reset, and the assert coverage metrics it will decrease."
Assert gen_strap_sample.StrapSampleOnce_A "assertion"
CHECKSUM: "4255502330 3554514034"
INSTANCE: tb.dut.u_reg.u_data_in
ANNOTATION: "Becasuse of the data_in is a read-only register, the signals wr_en and wr_data are not applicable. So those lines 43 and 44 are not hit by the testbench."
Branch 1 "1017474648" "(!rst_ni)" (2) "(!rst_ni) 0,0"
